// Code generated by Kitex v0.7.2. DO NOT EDIT.
package feedbackservice

import (
	server "github.com/cloudwego/kitex/server"
	feedback "github.com/li1553770945/personal-feedback-service/kitex_gen/feedback"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler feedback.FeedbackService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
